export { Channel } from './Channel';
export { Emoji } from './Emoji';
export { Event } from './Event';
export { Guild } from './Guild';
export { Message } from './Message';
export { Presence } from './Presence';
export { PresenceCount } from './PresenceCount';
export { Raw } from './Raw';
export { Role } from './Role';
export { Settings, SettingsEntity } from './Settings';
export { User } from './User';

import { Channel } from './Channel';
import { Emoji } from './Emoji';
import { Event } from './Event';
import { Guild } from './Guild';
import { Message } from './Message';
import { Presence } from './Presence';
import { PresenceCount } from './PresenceCount';
import { Raw } from './Raw';
import { Role } from './Role';
import { SettingsEntity } from './Settings';
import { User } from './User';
export default [Channel, Emoji, Event, Guild, Message, Presence, PresenceCount, Raw, Role, SettingsEntity, User];